[[pages]]
path = "home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
name = "Electronics"
icon = "âš¡"
is_section = true

[[pages]]
path = "electronics/op_amp.py"
name = "Op Amp"
icon = ":books:"

[[pages]]
name = "Algorithms"
icon = "ğŸˆï¸"
is_section = true

[[pages]]
path = "algorithms/sorting.py"
name = "Sorting"
icon = "ğŸ’ª"
